version: 2

jobs:
  test:
    working_directory: ~/circle-gh-tee
    docker:
      - image: 'rust:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v2-cargo-{{ arch }}
      - run: cargo test
      - run: cargo run -- echo -- it works
      - save_cache:
          key: v2-cargo-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - ~/circle-gh-tee/target

workflows:
  version: 2
  test:
    jobs:
      - test
